# .github/actions/setup/action.yml

name: 'Setup Python and Poetry'
description: 'Setup Python 3.10, Install and Configure Poetry, Cache Virtual Environment, and Install Dependencies'

inputs: {} # No inputs for now

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Cache Poetry
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/Python/3.10.13/x64/bin/
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}

    - name: Install Poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: |
        python -m pip install poetry==1.5.1
      shell: bash

    - name: Verify Poetry Installation Path
      run: |
        which poetry || true
      shell: bash

    - name: List contents of .poetry directory
      run: |
        ls -la ~/.poetry || true
      shell: bash

    - name: Configure Poetry
      run: |
        python -m poetry config virtualenvs.in-project true
      shell: bash

    - name: Cache the Virtual Environment
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: |
        python -m poetry install
      shell: bash
