# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# The poetry part was stolen from:
# https://joaodlf.com/using-poetry-in-github-actions-the-easy-way.html

name: Test and Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python, Poetry, and Dependencies
      uses: ./.github/actions/setup

    - name: Run Tests with Pytest
      run: |
        python -m poetry run python -m pytest -sxv

    - name: Check with Mypy
      run: |
        python -m poetry run python -m mypy .

    - name: Lint with Pylint
      run: |
        python -m poetry run python -m pylint $(git ls-files '*.py')
